use_frameworks!

platform :ios, '9.0'

target 'BasicKitApp' do
  pod 'BasicKit', :path => '../'
  
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'LookinServer', :configurations => ['Debug']
  pod 'FLEX', :configurations => ['Debug']
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'SDWebImage'

  target 'BasicKitTests' do
    inherit! :search_paths

    
  end
end
